name: "SBOM generation and scanning"
description: "Generate SBOM and scan for vulnerabilities"
author: "Joseph Pringle"
outputs:
  sbom-file:
    description: "The syft generated SBOM"
    value: ${{ steps.sbom-gen-and-scane.outputs.sbom-file }}
runs:
  using: "docker"
  image: "Dockerfile"
